### ISSUE TITLE
Email Change does not persist to database

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#100]
The new email is not added to the customer

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, das hier war dneke ich die eigentliche ursache fpr #118 und ist jetzt behoben. Würde mich freuen, wenn du das einmal testen könntest :)

**Comment by ursulafeu** [comment]
Ich hab heute ein paar verschickt - ging wunderbar.
