### ISSUE TITLE
Kundendaten im Kurs heranziehen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#110]
Lieber Andreas,
wenn ein Kunde seine Daten geändert haben möchte, muss man die Daten nicht nur beim Kunden aktualisieren, sondern auch bei allen Kursen, für die er sich angemeldet hat.
Kannst Du es so machen, dass die Kundendaten immer vom Kunden herangezogen werden?
Danke, Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, das ist dieses Ticket hier und leider ein ziemlicher Eingriff in das Herz des Systems - https://github.com/viszerale-therapie/simple-courses/issues/93 

Ist nach dem Kurspdf die nächste größere Baustelle, die ich anfangen würde.
