### ISSUE TITLE
change transportation email

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#113]
can you please remove Florindas name at the bottom of the transportation email.

Please write (instead of: Liebe Grüße und gute Anreise, ...)

Mit freundlichen Grüßen,
Schule für Viszerale Therapie

Thank you!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, 
it is changed and can be tested after the next deployment. (Later today)

Best wishes

**Comment by Andreas-Schoenefeldt** [comment]
deployed now :)

**Comment by ursulafeu** [comment]
danke!
