### ISSUE TITLE
new customer data entry: "Diploma provided"

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#122]
Dear Andreas,
before the course we have to check if participants sent in their diploma (proving that they are physiotherapist or doctor). At the moment we search manually for every course, for every customer and look through a list of PDF documents wether the customers diploma is in there or not.
This takes a lot of time.

Can you please add another record for the customer that will also be shown in the **course detail overview?** Please have a look at the screenshot below.

It is not necessary to show this field in the customer list overview. 
--> So I would like to insert this information at the customer and I will need it when checking the course detail overview.

![diploma](https://user-images.githubusercontent.com/23695891/31564715-3bd11774-b064-11e7-869d-ac709f82d366.jpg)

**Comment by Andreas-Schoenefeldt** [comment]
Das sollten wir zusammen mit #93 machen, bedeutet aber leider nen ziemlichen umbau der Datenstruktur. Da brauche ich etwas Ruhe für - soll das eher vor oder nach dem Anmedlungs PDF passieren?

**Comment by Andreas-Schoenefeldt** [comment]
Machen wir erstmal nur am Kunden

**Comment by ursulafeu** [comment]
hi Andreas, ich hoffe ihr seid gut ins neue Jahr gestartet. Könntest Du das bitte einbauen, wäre für den Workflow wirklich eine richtige Erleichterung. Danke!

**Comment by Andreas-Schoenefeldt** [comment]
Ok, ist ja nur eine Kleinigkeit :)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 

das sollte jetzt implementiert und live sein. Du kannst die checkbox sowohl am customer, als auch an der registrierung setzen (es wird dann entsprechend aktualisiert).

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke - Funktionalität perfekt!
Die Headline wird nicht richtig ausgegeben: [missing: headlines.customerDiplomaProvided]
Da könntest Du bitte einfach schreiben: 
"Diploma provided" statt "Diploma provided and checked"
