### ISSUE TITLE
"Close-Email" Issue

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#130]
Lieber Andreas,
jetzt haben wir einen live-Fall. 
Beim Kurs 294 (der letzte Kurs in Polen) wollte ich den Kurs nun abschließen, OHNE dass eine Email an einen einzigen Teilnehmer geht. 
Das ist ja nötig, um beim Kunden den Kurs als absolviert zu hinterlegen. Da hängt sich das System irgendwie auf. Kannst Du das bitte checken?
Danke! LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Alle waren Teilnehmer? Um es selber einmal abschicken zu können.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
ja, alle waren Teilnehmer - danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,

der ist jetzt behoben, dauert aber noch einen Moment, bis ich das deployment mache - ich meld mich dann.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke!
