### ISSUE TITLE
Kurs 277 - Close Course Email wieder nicht geklappt

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#134]
Lieber Andreas,
ich hab grad den Kurs 277 abgeschlossen. Dann bekomme ich auf die info Adresse das Abschluss Email, aber im Backend bleibt das Fenster ewig offen und das Rädchen dreht und dreht sich. Ich hab nach einer halben Stunde dann eine Reload gemacht, da hat sich offensichtlich was aufgehängt?!
kannst Du bitte checken, ob die Emails rausgingen?
danke! LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

ja wenn du die email bekommen haben, haben auch die anderen sie bekommen. Kannst du bitte einmal deinen browser cache leer machen? Da ist bestimmt noch der alte code bei dir gelaufen (das mit dem endlos Rädchen)

Liebe Grüße
Andreas
