### ISSUE TITLE
Registration Form: Capital letters

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#138]
kannst Du die automatische Kleinschreibung beim Feld "Straße / Hausnummer" entfernen, geht das?
Ich muss bei allen Anmeldungen die Adresse manuell nachbessern, wenn die Straße aus mehr als einem Wort besteht. Das ist in Summe einiges an Zeit, die ich dafür verwenden.
Danke! LG; Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Fixed togather with https://github.com/viszerale-therapie/simple-courses/issues/162
