### ISSUE TITLE
Textergänzung im Rechnungs-PDF

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#142]
Lieber Andreas,
kannst Du im Rechnungs-PDF einen Satz ergänzen: 
In diesem Betrag ist keine Umsatzsteuer enthalten.

--> siehe PDF anbei. Danke!
[Cassar_Irina_18_302.pdf](https://github.com/viszerale-therapie/simple-courses/files/1671649/Cassar_Irina_18_302.pdf)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

die Änderung ist Live.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
das ist ja spitze - vielen Dank!!
