### ISSUE TITLE
Customer Daten - bitte neues Feld "keine Werbung per Post"

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#146]
Lieber Andreas,
kannst Du bitte beim Kunden ein neues Feld einfügen, das auch nur über die Customer List sichtbar sein soll. "Keine Werbung per Post"
Vielen lieben Dank! Ursula

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula,
wenn du den cache löschst (muss man leider immer noch), kannst du es jetzt sehen und setzen.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
super! danke.
