### ISSUE TITLE
Übernachtungsmöglichkeiten - Textänderung

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#150]
Bitte beim Gästehaus Wagner Daten ändern wie folgt - danke!
(ich habe auf das Template keinen Zugriff über das Backend)

rosemarie.e@sbg.at ändern auf mathilde.eder@aon.at  
Tel: 06217 70 42 oder 0664 3718954

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, 

die Übernachtungsaddressen lassen sich alle bei den Locations einstellen: http://backend.viszerale-therapie.at/show/Location

<img width="679" alt="screen shot 2018-03-28 at 13 14 15" src="https://user-images.githubusercontent.com/1157580/38025805-fbd34324-3289-11e8-89d0-e53934707ca0.png">

Das ist es, was geändert werden muss, oder?

Liebe Grüße
Andreas
