### ISSUE TITLE
Titel entfernen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#155]
Bitte den Titel **Dipl. PT** löschen. 
Soll nicht mehr zur Verfügung stehen, dieser Titel ist gesetzlich verboten (gabs früher mal). 
Danke!

**Comment by Andreas-Schoenefeldt** [comment]
Im Frontend ist er schon nicht mehr auswählbar

**Comment by ursulafeu** [comment]
OK, dann ist das sicher noch von alten Anmeldungen ... danke!
