### ISSUE TITLE
Übernachtungsmöglichkeiten - Adresse hinzufügen

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#160]
Lieber Andreas,
kannst Du bitte bei den Übernachtungsmöglichkeiten im Template "Registration Confirmation Email - Customer" noch folgende Adresse hinzufügen:

Souterrain-Privatzimmer "Genusshaus"
Brunnenweg 9 (ca. 7 Gehminuten)
Tel. 0660 5969002 sowie 0660 655 88 55
namaste@yogamantra.at

Vielen Dank!

**Comment by Andreas-Schoenefeldt** [comment]
Liebe Ursula,

die Liste der Hotels lässt sich direkt an der Location pflegen: https://backend.viszerale-therapie.at/show/Location

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Danke! Eventuell bleibt das jetzt auch mal hängen bei mir und ich frag Dich nächstes Mal nicht mehr ... ;)
