### ISSUE TITLE
Email ändern bei Kurs-TN

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#161]
Lieber Andreas, 

ich habe wieder einen "Email-Fall" - Ingrid Walkner (customer ID 376) möchte Ihre Email-Adresse ändern auf: walkner-anders@tele2 
Sie ist aktuell auch bei Kurs 348 angemeldet. 

Ich kann die Email weder beim Kurs noch beim Kunden ändern - bitte um Hilfe, vielen Dank!

**Comment by Andreas-Schoenefeldt** [comment]
Da fehlt ein .com oder .at, wenn mich nicht alles täuscht, oder?

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
oh mann, das ist ja peinlich. Ich hatte heute so viel zu tun, da überseh ich manchmal das Offensichtliche. danke!
