### ISSUE TITLE
Anmeldung (bei Doppelname- zweiter Name kann nicht groß geschrieben werden)

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#162]
- WO? http://frontend-test.czeija.com/de/register/1?course-id=239
- Unter: Verbindliche Anmeldung zum Kurs: Feld "Vorname" 
Doppelname versucht einzutragen (Hans Joachim) > 2. Vorname kann nicht groß geschrieben werden

![grafik](https://user-images.githubusercontent.com/44013971/51697401-b532a100-1fd5-11e9-96b2-95b9ce3c07ed.png)

**Comment by nmxmx** [comment]
Identisches Problem, wenn es einen 2. Nachnamen gibt. Dieser lässt sich nicht groß schreiben auch wenn es z.B. mit einem Bindestrich getrennt ist.

**Comment by Andreas-Schoenefeldt** [comment]
Der Fehler ist ähnich wie  #138 - die logic muss etwas ergänzt werden um - und eerzeichen bei entsprechenden Worten mit in Betracht zu ziehen.

**Comment by nmxmx** [comment]
Weiterhin schreibt das System den 2. Vornamen oder den 2. Nachnamen immer in Kleinbuchstaben

![grafik](https://user-images.githubusercontent.com/44013971/54489976-2e51c480-48b2-11e9-9bdf-bbe09ec6c7cc.png)

**Comment by Andreas-Schoenefeldt** [comment]
Now it actually works ;)
