### ISSUE TITLE
Anmeldung Land-Liste ("Bitte Land wählen" in der Liste)

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#163]
- WO?: http://frontend-test.czeija.com/de/register/1?course-id=239
- Land: In der Liste findet man unter dem Buchstaben B "Bitte Land auswählen"
- Vorschlag/ Idee: In der Liste steht als erstes immer Österreich!? Soll das bestehen bleiben? Ggf. zusätzlich ganz oben auch Deutschland aufführen? 

![grafik](https://user-images.githubusercontent.com/44013971/51697959-1dce4d80-1fd7-11e9-8606-01dc6e783a65.png)

**Comment by Andreas-Schoenefeldt** [comment]
I removed the Bitte Land wählen from the list :)
