### ISSUE TITLE
Anmeldebestätigung- Datum fehlerhaft

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#164]
- Wo? http://frontend-test.czeija.com/de/submit/1
- Anmeldebestätigung: Datum stimmt nicht mit dem Datum auf der Frontpage überein
Datum Frontpage: 03.09 - 07.09.2016 / Datum Anmeldebestätigung: 24.01 - 24.01.2019 

![grafik](https://user-images.githubusercontent.com/44013971/51698784-1f007a00-1fd9-11e9-8d86-848a195bb202.png)

**Comment by nmxmx** [comment]
Identischer Fehler bei Kursbuchung (Warteliste): Läsionskette, Verdauungstrakt – Wirbels. | 27.09 – 01.10.2016 mit Elfi Schlager (Kurs ID 240)
![grafik](https://user-images.githubusercontent.com/44013971/51713246-5e41c180-1fff-11e9-997e-6a79c5d7bcf1.png)

**Comment by nmxmx** [comment]
Fehler beständig

![grafik](https://user-images.githubusercontent.com/44013971/54460457-e6278a80-4769-11e9-8e6d-bbffc0ce42c6.png)

**Comment by Andreas-Schoenefeldt** [comment]
Danke dafür! Hab's gefunden und gefixed.
