### ISSUE TITLE
Courses- Datum fehlerhaft

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#165]
WO: http://backend-test.czeija.com/show/Course/?filter=dissabled%3A0%7ClocationID%3A4
Verlauf: 
- Anmeldung für Kurs "Läsionskette, Verdauungstrakt – Wirbels./ 03.09 - 07.09.2016/ 570,00€/ Danzig/Polen/ Florinda Czeija
- Anmeldebestätigung Page: Läsionskette Verdauungstrakt – Wirbelsäule - 5 Tage, 570,- €/ Termin: 24.01 - 24.01.2019 (BUG für Datum unter #164 )
-Check unter Courses- Datum fehlerhaft (ID 239) siehe Screenshot 1
- Klick auf ID 239 für Details- Datum fehlerhaft -siehe Screenshot 2

![grafik](https://user-images.githubusercontent.com/44013971/51699305-6cc9b200-1fda-11e9-900c-b3cd72df1191.png)

![grafik](https://user-images.githubusercontent.com/44013971/51699516-ec578100-1fda-11e9-93d7-5d95484925a8.png)

**Comment by Andreas-Schoenefeldt** [comment]
Fixed with #166.
