### ISSUE TITLE
Move this registration to the waitinglist- Fehlerhafte Anzeige der Mail

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#167]
WO? http://backend-test.czeija.com/Course/239
Ablauf: 
- Person für Kurs registriert
- Move this registration to the waitinglist
- Fenster öffnet sich
- Haken bei "Notify the customer via email?" gesetzt
- Klick auf "YES" > Funktioniert jedoch Mail an registirierte Person fehlerhaft 
(Betreffzeile/ [property streetAddress not found in customerAddress]
[property zip not found in customerAddress] [property city not found in customerAddress]

![grafik](https://user-images.githubusercontent.com/44013971/51703021-465c4480-1fe3-11e9-864d-7cb292f62652.png)
![grafik](https://user-images.githubusercontent.com/44013971/51703055-5c6a0500-1fe3-11e9-9b8e-95d6f2bca04d.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hi Nicole, ich hab den ersten Fehler gefunden, aber bist du sicher, das diese Email versendet wurde? Das passt irgendwie nicht.

Danke für den double check.

**Comment by nmxmx** [comment]
Ist gefixt!!! 
Allerdings gibt es einen Rechtschreibfehler in der Mail (bei den Kurszeiten > letzter!!)
![grafik](https://user-images.githubusercontent.com/44013971/55353129-cfe83100-54c2-11e9-8dbf-72f1aee68d64.png)
