### ISSUE TITLE
Von der Warteliste zum Kurs hinzufügen- Error while sending email

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#168]
WO?
Ablauf: 
- Teilnehmer von Warteliste zum Kurs hinzufügen "Allow for participation"
- neues Fenster öffnet sich, Haken bei "Notify the customer via email?"
- Klick auf "YES"
- rechts rotes Fenster: "Error while sending email"
(Mail an Teilnehmer kommt nicht an)

![grafik](https://user-images.githubusercontent.com/44013971/51703544-a0113e80-1fe4-11e9-8556-e13cc6b3d26a.png)

**Comment by nmxmx** [comment]
Fenster schließt sich nicht von alleine, da Fehler bei errow while sending email
Fenster schließt sich nur, wenn man auf close klickt

**Comment by Andreas-Schoenefeldt** [comment]
Sollte zusammen mit #167 erledigt sein :)

**Comment by nmxmx** [comment]
Sieht gut aus, Fehler nicht nochmal aufgetreten
