### ISSUE TITLE
Mailvorschau mit Klammern

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#173]
WO: 

- http://backend-test.czeija.com/show/Registration/item/3063/preview-any-email
-# Course 243 -in Warteliste geschoben
- Allow to participation
- klick auf "preview the current email.."

- ![grafik](https://user-images.githubusercontent.com/44013971/55110157-b5374600-50d7-11e9-9481-f0dce381c21a.png)

**Comment by Andreas-Schoenefeldt** [comment]
Ah yes, da steckt noch irgendwo der Wurm drin. Danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hi Nicole,
ich hab nach etwas suchen die Ursache in #174 gefunden - leider sind alle alten Anmeldungen im Test- System schon mit unvollständigen Daten versehen.  

Wenn du das noch einmal testest, bitte mit neuen Anmeldungen :).

**Comment by nmxmx** [comment]
Hallo Andreas,
wie schnell brauchst du die jeweiligen Test? Ich kann jetzt kurz ein paar Sachen checken aber dann ggf erst wieder ab Samstag. Reicht dir das?



Von: Andreas Schönefeldt <notifications@github.com>
Gesendet: Montag, 1. April 2019 20:46
An: viszerale-therapie/simple-courses <simple-courses@noreply.github.com>
Cc: Nicole Meixner <kontakt@nicolemeixner.de>; Assign <assign@noreply.github.com>
Betreff: Re: [viszerale-therapie/simple-courses] Mailvorschau mit Klammern (#173)


Hi Nicole,
ich hab nach etwas suchen die Ursache in #174<https://github.com/viszerale-therapie/simple-courses/issues/174> gefunden - leider sind alle alten Anmeldungen im Test- System schon mit unvollständigen Daten versehen.

Wenn du das noch einmal testest, bitte mit neuen Anmeldungen :).

**Comment by nmxmx** [comment]
Sieht gut aus. 
Siehe #167 sieht mir nach dem identischen "Problem" mehr oder weniger aus.
