### ISSUE TITLE
Invoice Nummer nicht automatisch gelistet

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#176]
WO: http://backend-test.czeija.com/Course/258?invoice-number-input=

- Kurs 258

- Manage Invoices klick (siehe Screenshot 1)

- freies Feld: Invoice start Number - befüllt und auf Fill geklickt aber nichts passiert

![grafik](https://user-images.githubusercontent.com/44013971/55354810-ee502b80-54c6-11e9-8301-8fa6b5a5bd12.png)

![grafik](https://user-images.githubusercontent.com/44013971/55354700-ab8e5380-54c6-11e9-9bc3-29538ba233c1.png)

**Comment by Andreas-Schoenefeldt** [comment]
great catch! I'll wait still a bit with the next deployment, but afterwards it can be retested :)
