### ISSUE TITLE
persönliche Email / sizen

### ISSUE THREAD

**Issue by nmxmx** [viszerale-therapie/simple-courses#177]
Wo?: http://backend-test.czeija.com/show/Registration/item/3068/preview-any-email

- Course 258 
- Klick auf "Manage Invoices"
- Nummer füllen/ Haken bei "persönliche Mail" (Screenshot 1)
- Mail Vorschau- nicht persönlich (Screenshot 2)

![grafik](https://user-images.githubusercontent.com/44013971/55355561-f4dfa280-54c8-11e9-9bd7-82949a06f756.png)

![grafik](https://user-images.githubusercontent.com/44013971/55355672-42f4a600-54c9-11e9-92a5-0c29dec275db.png)

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

brauchst du das persönliche Email feature hier überhaupt? Sonst nehm ich einfach die ganze Zeile raus.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Lieber Andreas, ich versteh leider die Frage nicht. 
Aber die Lösung wie es im Test-Backend ist, dass ich den Email-Text bei den Templates selbst schreiben kann ist super.

**Comment by Andreas-Schoenefeldt** [comment]
Also verwendest du die "personal Email" checkbox nicht, richtig? Bei den Rechnungen hatte ich das damals für Florinda engebaut, weil sie vielen ihrer Kunden gerne eine persöhnlichere email schicken wollte.

**Comment by ursulafeu** [comment]
Nein, das Feld verwende ich nicht. Das hab ich bisher gar nicht beachtet, ich wüßte gar nicht, wie man das bedient. ;) Also ... brauchen wir nicht bei den Foldern.

**Comment by Andreas-Schoenefeldt** [comment]
Done, the checkbox is gone :)
