### ISSUE TITLE
Utilize the paste plugin

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#180]
To avoid all the word jumk html spans: https://www.tiny.cloud/docs/plugins/paste/

**Comment by Andreas-Schoenefeldt** [comment]
Done :)

**Comment by Andreas-Schoenefeldt** [comment]
@ursulafeu, im neuesten Release ist jetzt auch am editor eingestellt, das er fast alle formatierungen beim einfügen entfernt - copy & paste aus Word sollte jetzt auch möglich sein :)

**Comment by ursulafeu** [comment]
sehr cool, danke!
