### ISSUE TITLE
Editor - Links setzen nicht mehr möglich

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#184]
Im neuen Editor kann man keine Links mehr setzen. Das Fenster öffnet sich, aber man kann nur Save oder cancel. Muss es momentan über HTML im Source Code lösen. 
danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

ich glaube sie haben einfach nur das overlay etwas angepasst, wenn man eine url einträgt und auf save clickt, wird der Link bei mir gesetzt.

<img width="478" alt="Screen Shot 2019-04-29 at 17 00 34" src="https://user-images.githubusercontent.com/1157580/56877255-c2619f00-6aa0-11e9-80ff-0d35aa5a5a4d.png">

Das Entfernen ist leider noch unintuitiver: Mann muss die url löschen und dann auch auf save clicken.

Das es sich hier um ein Standardmodul des Editors handelt, müssen wir leider damit leben.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
danke fürs Prüfen, ist Browserabhängig. Mit Firefox funktionierts. Dann arbeite ich einfach damit.

**Comment by Andreas-Schoenefeldt** [comment]
Ah I see - bei welchem geht es nicht?

**Comment by ursulafeu** [comment]
bei Safari, aber wie gesagt ich kann auch einfach in Firefox arbeiten. danke!

**Comment by Andreas-Schoenefeldt** [comment]
Alright, bei mir im Safari geht es auch - closed again.
