### ISSUE TITLE
Email preview funktioniert nicht mehr

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#185]
lieber Andreas, 
bei dem Button (siehe rot im Screenshot) passiert leider nix mehr. Da ging immer das Email als preview in einem eigenen Tab auf. Kannst Du das bitte wiederherstellen. Danke!
![email-preview](https://user-images.githubusercontent.com/23695891/55964131-72977100-5c74-11e9-8bf5-daf4d7ef80d6.png)

**Comment by Andreas-Schoenefeldt** [comment]
Ups, small mistake, which is fixed now.

**Comment by ursulafeu** [comment]
funktioniert bei der Transport information Email leider nach wie vor nicht - ist dann vielleicht der Grund für Ticket #207 ?

**Comment by Andreas-Schoenefeldt** [comment]
This works now again :).

**Comment by ursulafeu** [comment]
das klappt, danke!!
