### ISSUE TITLE
Bitte PDF-Dateiname für Übernachtungsmöglichkeiten ändern

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#188]
Lieber Andreas, bei der Anmeldebestätigungs-Email ist das PDF mit den Übernachtungsmöglichkeiten angehängt. Da heißt das PDF "Anfahrt_Salzburg_Schloss_Mattsee.pdf" - kannst Du das bitte auf "Übernachtung_Schloss_Matsee" ändern.

danke!

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula, das ist jetzt geändert :)

**Comment by ursulafeu** [comment]
danke!
