### ISSUE TITLE
Make it impossible to save internationalized text fields without the default language fallback

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#192]
Might lead otherwise to strange issues in the frontend display.

**Comment by Andreas-Schoenefeldt** [comment]
Done :)

**Comment by Andreas-Schoenefeldt** [comment]
@ursulafeu, um dich etwas vorzuwarnen, die Internationalen Eingabemasken lassen dich jetzt nicht mehr durch, wenn der englische Text fehlt ;)

**Comment by ursulafeu** [comment]
alles klar, macht Sinn :)
