### ISSUE TITLE
Restore the xml export

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#195]
For symphony 3 this bundle seems to be a good option: https://github.com/MewesK/TwigSpreadsheetBundle

**Comment by Andreas-Schoenefeldt** [comment]
In the end I took https://phpspreadsheet.readthedocs.io/en/latest/

**Comment by Andreas-Schoenefeldt** [comment]
Hi Ursula, this is working now again :)

**Comment by Andreas-Schoenefeldt** [comment]
Leider doch nicht - auf dem server fehlt eine php extension... Ich habe den Support angefragt.

**Comment by Andreas-Schoenefeldt** [comment]
Der Support hat jetzt die fehlende Extension aktiviert - es geht jetzt wieder :)

**Comment by ursulafeu** [comment]
danke!
