### ISSUE TITLE
Long double names in the name cards

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#196]
Hi Ursula,

If a certain character length is for the name cards reached, the font should be smaller I guess?

See here the example of Mag. Marie Luise:

<img width="401" alt="Screen Shot 2019-06-16 at 23 59 56" src="https://user-images.githubusercontent.com/1157580/59579588-efdfc780-90a3-11e9-81e6-b1eb0b5c194e.png">

**Comment by ursulafeu** [comment]
yes please! I always had to correct this manually. If it is possible automatically that would be really nice. :))

**Comment by Andreas-Schoenefeldt** [comment]
Ok, der Text passt sich jetzt etwas besser von selbst an - bei seeeeeeehr langen namen kann es sein das es zu klein wird, schauen wir dann aber im Einzelfall würde ich sagen ;)

**Comment by ursulafeu** [comment]
sehr gut! danke. :)
