### ISSUE TITLE
Überbuchung Kurs ID 377

### ISSUE THREAD

**Issue by ursulafeu** [viszerale-therapie/simple-courses#197]
Beim oben genannten Kurs konnten sich 29 Personen anmelden, obwohl die max TN-Zahl auf 28 Personen ist. Kannst Du bitte prüfen, wie das zustande gekommen ist. 
Und welchen TN soll ich jetzt wieder "rausschmeißen"? ;) Da hab ich auch entsprechenden Erklärungsbedarf. Da hilft mir eine technisch versierte Antwort, wenn es eine gibt. Vielleicht muss ich sonst einfach extrem kreativ sein ... 
danke!! Liebe Grüße, Ursula

**Comment by ursulafeu** [comment]
Lieber Andreas, kannst Du mir da bitte Bescheid sagen, ich muss einen der Kursteilnehmer wieder aus dem Kurs nehmen und ich würde das gerne asap erledigen. Vielen Dank!

**Comment by Andreas-Schoenefeldt** [comment]
Yes, der versuchte quick-fix am Freitag hat leider nicht funktioniert. Ich mache das heute mit hoher Prio weiter.

**Comment by ursulafeu** [comment]
Danke! 👍

Von meinem iPhone gesendet

> Am 24.06.2019 um 14:52 schrieb Andreas Schönefeldt <notifications@github.com>:
> 
> Yes, der versuchte quick-fix am Freitag hat leider nicht funktioniert. Ich mache das heute mit hoher Prio weiter.
>

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Liebe Ursula,

also ich habe mal die logs durchgeschaut und zur Anmeldung von Simone S (der letzten Anmeldung) folgendes gefunden:

```
[2019-06-02 20:48:43] registration.INFO: Customer Registration Start {"course":"377","email":"p...@gmx.net"} []
[2019-06-02 20:48:43] registration.INFO: Customer Registration Success {"course":"377","name":"Simone S","email":"p...@gmx.net","position":"WL"} []
[2019-06-02 20:50:03] registration.INFO: post-processing of registration 5750 {"course":377,"registration":5750,"name":"Simone S","email":"p...@gmx.net","position":"WL"} []
[2019-06-02 20:50:03] registration.INFO: Registration linked to Customer Simone Stamer () [] []
[2019-06-02 20:50:03] registration.INFO: Generating Location PDF [] []
[2019-06-02 20:50:06] registration.INFO: Generating dynamic PDF  [] []
[2019-06-02 20:50:07] registration.INFO: customer registration pdf created {"course":377,"registration":5750,"name":"Simone S","email":"p...@gmx.net","position":"WL"} []
[2019-06-02 20:50:07] registration.INFO: Email to customer send {"course":377,"registration":5750,"name":"Simone S","email":"p...@gmx.net","position":"WL"} []
[2019-06-02 20:50:07] registration.INFO: Admin email send to info@viszerale-therapie.at {"course":377,"registration":5750,"name":"Simone S","email":"p...@gmx.net","position":"WL"} []
```

Sie wurde richtig für die Warteliste (WL) eingetragen, warum sie jetzt als normaler Teilnehmer erscheint, kann ich nicht sagen (da ich den Vorgang nicht logge) würde aber sagen, das es ein versehen war. Eventuell hat sie die Bestätungsemail für die Teilnahem auch gar nicht bekommen - falls sie kein Geld überweisen hat, ist das ziemlich warscheinlich denke ich.

Ich denke die Wahl ist klar, ich hoffe ich konnte den Fall etwas mehr lüften :)

Wenn du es für hilfreich erachtest, baue ich auch gerne noch ein paar mehr logs zu den konkreten Statuswechseln im Kurs ein.

Liebe Grüße
Andreas

**Comment by Andreas-Schoenefeldt** [comment]
Mein Kommentar von heute morgen hatte sich auf das excel ticket bezogen ;) - bin aber froh, das du mich hier nocheinmal erinnert hast - ist mal wieder crazy im Moment.

**Comment by ursulafeu** [comment]
Lieber Andreas, danke fürs Prüfen! 
Ich denke zum Thema Warteliste ist da vielleicht was ominöses im Hintergrund am Laufen – bei den Anatomiekursen konnten sich mehr als fünf Teilnehmer auf die Warteliste setzen lassen.
Konnte man das nicht mal beim Kurs-Type direkt hinterlegen, wieviele auf die Warteliste kommen sollen?

**Comment by ursulafeu** [comment]
Lieber Andreas, danke fürs Prüfen! 
Ich denke zum Thema Warteliste ist da vielleicht was ominöses im Hintergrund am Laufen – bei den Anatomiekursen konnten sich mehr als fünf Teilnehmer auf die Warteliste setzen lassen.
Konnte man das nicht mal beim Kurs-Type direkt hinterlegen, wieviele auf die Warteliste kommen sollen?

**Comment by ursulafeu** [comment]
Also die Dame hat sich über Warteliste angemeldet und eine normale Anmeldebestätigung bekommen. Ich hab das aber ganz elegant gemacht, sie freut sich total über ihren ersten Platz auf der Warteliste.

**Comment by ursulafeu** [comment]
Hast Du schon mal geschaut, warum bei den Anatomie-Kursen so viele auf die Warteliste gekommen sind?

**Comment by Andreas-Schoenefeldt** [comment]
Ich habe die Aufteilung ungeschickt gemacht - die Begrenzung der Warteliste ist im frontend konfiguriert und das Backend nimmt einfach alle auf. Ich werde das mit diesem Ticket ändern, so dass es im Backend steht und auch bei einem caching der Seite nicht umgangen werden kann.

**Comment by ursulafeu** [comment]
sehr gut, danke.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo @ursulafeu,

die maximale Wartelistengröße wird jetzt über eine config in Backend gesteuert, damit ist kein überbuchen mehr möglich :)

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
perfekt, danke!
