### ISSUE TITLE
Unterschiedliche Kurszeiten für den Anatomie kurs

### ISSUE THREAD

**Issue by Andreas-Schoenefeldt** [viszerale-therapie/simple-courses#215]
![WhatsApp Image 2019-12-02 at 14 29 13](https://user-images.githubusercontent.com/1157580/70156527-d4d53400-1692-11ea-89d8-78b0df442cc1.jpeg)

optionales feld im backend am kurs, das erlaubt start und endzeit zu definieren - wenn die Zeiten definiert sind wird anstelle des Lehreres im frontend die Zeit angezeigt.

![WhatsApp Image 2019-12-03 at 08 40 53](https://user-images.githubusercontent.com/1157580/70090075-30061880-15f8-11ea-8e06-d730426ec987.jpeg)

Lieber Andreas, bitte denk auch dran, dass Uhrzeitinfo (neues Feld) unbedingt auch in der Email für uns (Admin-Email) und in der Kunden-Anmeldeemail dabei stehen muss. Danke!

![WhatsApp Image 2019-12-03 at 08 41 54](https://user-images.githubusercontent.com/1157580/70090082-33010900-15f8-11ea-98ee-7ffbf8b0222b.jpeg)
Und hier brauche ich auch das Feld sichtbar bitte.

**Comment by Andreas-Schoenefeldt** [comment]
Hallo Ursula,

du kannst jetzt Zeiten individuell am Kurs mit eintragen - ich denke ich habe alle Stellen erwischt, aber meld dich bitte, wenn es noch irgendwo fehlt.

Liebe Grüße
Andreas

**Comment by ursulafeu** [comment]
Lieber Andreas, danke fürs super flotte Umsetzen!! 
Der Newsletter kann wohl raus ... und die Anmeldungen rein. :)
DANKE!
